### ISSUE TITLE
windows kafka启动报错

### ISSUE THREAD

**Issue by orangeyts** [cwenao/springboot_cwenao#1]
兄弟，遇到过window 下kafka启动这个问题么？

D:\chromeDownload\kafka_2.12-0.10.2.1\bin\windows>kafka-server-start.bat ../../c
onfig/server.properties
[2017-09-18 12:52:21,997] FATAL  (kafka.Kafka$)
java.lang.VerifyError: Uninitialized object exists on backward branch 162
Exception Details:
  Location:
    scala/util/matching/Regex.unapplySeq(Lscala/util/matching/Regex$Match;)Lscal
a/Option; @216: goto
  Reason:
    Error exists in the bytecode
  Bytecode:
    0000000: 2bc6 000a 2bb6 00ef c700 07b2 0052 b02b
    0000010: b600 f2b6 00f3 2ab6 0054 4d59 c700 0b57
    0000020: 2cc6 000d a700 c92c b600 f799 00c2 bb00
    0000030: 6059 b200 65b2 006a 043e c700 0501 bf1d
    0000040: 2bb6 00f8 b600 74b6 0078 2bba 0100 0000
    0000050: b200 93b6 0097 3a06 3a05 59c7 0005 01bf
    0000060: 3a04 1906 b200 93b6 009b a600 7619 04b2
    0000070: 00a0 a600 09b2 00a0 a700 71bb 00a2 5919
    0000080: 04b6 00a8 3a0b 2b19 0bb8 00fc b200 a0b7
    0000090: 00ac 3a07 1907 3a08 1904 b600 afc0 00a4
    00000a0: 3a09 1909 b200 a0a5 0034 bb00 a259 1909
    00000b0: b600 a83a 0b2b 190b b800 fcb2 00a0 b700
    00000c0: ac3a 0a19 0819 0ab6 00b3 190a 3a08 1909
    00000d0: b600 afc0 00a4 3a09 a7ff ca19 07a7 000c
    00000e0: 1904 1905 1906 b800 b9b7 00bc b02a 2bb6
    00000f0: 00ef b601 02b0
  Stackmap Table:
    same_frame(@11)
    same_frame(@15)
    full_frame(@39,{Object[#2],Object[#34],Object[#86]},{Object[#86]})
    same_frame(@46)
    full_frame(@63,{Object[#2],Object[#34],Object[#86],Integer},{Uninitialized[#
46],Uninitialized[#46],Object[#98]})
    full_frame(@96,{Object[#2],Object[#34],Object[#86],Integer,Top,Object[#206],
Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#164]})
    full_frame(@123,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@162,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{U
ninitialized[#46],Uninitialized[#46]})
    full_frame(@219,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208],Object[#162],Object[#162],Object[#164],Top,Object[#4]},{U
ninitialized[#46],Uninitialized[#46]})
    full_frame(@224,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46]})
    full_frame(@233,{Object[#2],Object[#34],Object[#86],Integer,Object[#164],Obj
ect[#206],Object[#208]},{Uninitialized[#46],Uninitialized[#46],Object[#4]})
    full_frame(@237,{Object[#2],Object[#34],Object[#86]},{})

        at scala.collection.immutable.StringLike.r(StringLike.scala:287)
        at scala.collection.immutable.StringLike.r$(StringLike.scala:287)
        at scala.collection.immutable.StringOps.r(StringOps.scala:29)
        at scala.collection.immutable.StringLike.r(StringLike.scala:276)
        at scala.collection.immutable.StringLike.r$(StringLike.scala:276)
        at scala.collection.immutable.StringOps.r(StringOps.scala:29)
        at kafka.cluster.EndPoint$.<init>(EndPoint.scala:29)
        at kafka.cluster.EndPoint$.<clinit>(EndPoint.scala)
        at kafka.server.Defaults$.<init>(KafkaConfig.scala:63)
        at kafka.server.Defaults$.<clinit>(KafkaConfig.scala)
        at kafka.server.KafkaConfig$.<init>(KafkaConfig.scala:616)
        at kafka.server.KafkaConfig$.<clinit>(KafkaConfig.scala)
        at kafka.server.KafkaServerStartable$.fromProps(KafkaServerStartable.sca
la:28)
        at kafka.Kafka$.main(Kafka.scala:58)
        at kafka.Kafka.main(Kafka.scala)

**Comment by orangeyts** [comment]
版本兼容性问题，

- kafaka换成kafka_2.9.1-0.8.2.1就可以了
- Java(TM) SE Runtime Environment (build 1.8.0-b132)
